In [17]:
import pandas as pd

# Load the new dataset
file_path = ("Open_Restaurants_Inspections_20250408.csv")
df_new = pd.read_csv(file_path)

# List all feature (column) names
feature_names = df_new.columns.tolist()

# Print them
print("Feature Names:")
for feature in feature_names:
    print(feature)

Feature Names:
Borough
RestaurantName
SeatingChoice
LegalBusinessName
BusinessAddress
IsRoadwayCompliant
Postcode
Latitude
Longitude
CommunityBoard
CouncilDistrict
CensusTract
BIN
BBL
NTA

In [3]:
import pandas as pd

# Set pandas to display all columns and expand column width
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# Load the CSV file (make sure the file is in your current working directory or provide the full path)
df = pd.read_csv("Open_Restaurants_Inspections_20250408.csv")

# Display the top 10 rows of the dataframe
df.head(5)

,Borough,RestaurantName,SeatingChoice,LegalBusinessName,BusinessAddress,RestaurantInspectionID,IsSidewayCompliant,IsRoadwayCompliant,SkippedReason,InspectedOn,AgencyCode,Postcode,Latitude,Longitude,CommunityBoard,CouncilDistrict,CensusTract,BIN,BBL,NTA
0,Manhattan,Oscar Wilde,both,Camelot Castle LLC,45 West 27th st,72891,NaN,Non-Compliant,NaN,12/20/2021 04:06:58 PM,DOT,10001,40.744876,-73.989657,5.0,3.0,58.0,1015677.0,1.008290e+09,Hudson Yards-Chelsea-Flatiron-Union Square
1,Manhattan,LA RUBIA RESTAURANT,both,LA RUBIA RESTAURANT INC,3517 BROADWAY,72892,NaN,For HIQA Review,NaN,12/20/2021 04:18:42 PM,DOT,10031,40.825863,-73.950874,9.0,7.0,229.0,1062369.0,1.020910e+09,Hamilton Heights
2,Manhattan,Thai Sliders,sidewalk,Silom Thai Inc,150 8th Ave,72893,NaN,Non-Compliant,NaN,12/20/2021 04:35:41 PM,DOT,10011,40.741906,-74.000945,4.0,3.0,81.0,1013845.0,1.007670e+09,Hudson Yards-Chelsea-Flatiron-Union Square
3,Brooklyn,Otway,both,St james 930 LLC,930 Fulton street,72894,NaN,Cease and Desist,NaN,12/20/2021 04:38:45 PM,DOT,11238,40.682833,-73.963833,2.0,35.0,201.0,3335112.0,3.020130e+09,Clinton Hill
4,Brooklyn,WILLIAMSBURG THAI CUISINE,both,WILLIAMSBURG THAI CUISINE NY INC,212 BEDFORD AVENUE,72896,NaN,Compliant,NaN,12/20/2021 04:52:41 PM,DOT,11249,40.716913,-73.958728,1.0,33.0,553.0,3062192.0,3.023350e+09,North Side-South Side

In [21]:
import pandas as pd

# Load the dataset
file_path = 'Open_Restaurants_Inspections_20250408.csv'  # Update path if needed
df = pd.read_csv(file_path)

# Filter to only include restaurants in Manhattan
df_manhattan = df[df['Borough'] == 'Manhattan']

# Columns to drop
columns_to_drop = [
    'IsSidewayCompliant',
    'AgencyCode',
    'SkippedReason',
    'InspectedOn',
    'IsRoadwayCompliant',
    'CommunityBoard',
    'CouncilDistrict',
    'CensusTract',
    'BIN',
    'BBL'
]


# Drop the specified columns if they exist
df_manhattan_cleaned = df_manhattan.drop(columns=[col for col in columns_to_drop if col in df_manhattan.columns])

# Display 10 random rows
print(df_manhattan_cleaned.sample(5))
df_manhattan_cleaned.head(5)

         Borough         RestaurantName SeatingChoice                LegalBusinessName          BusinessAddress  RestaurantInspectionID  Postcode   Latitude  Longitude                      NTA
7079   Manhattan               Tre Otto          both                      UNI NYC LLC      1410 Madison Avenue                   80689     10029  40.788313 -73.953379        East Harlem South
23729  Manhattan         PINGS NYC Inc.          both                   Pings NYC Inc.           22 MOTT STREET                  109781     10013  40.714316 -73.998756                Chinatown
27131  Manhattan                ATTABOY       roadway            ATTABOY COCKTAILS LLC          134 ELDRIDGE ST                   11612     10009  40.718913 -73.991566                Chinatown
20125  Manhattan          ROSA MEXICANO          both  ROSA MEXICANO SECOND AVENUE LLC     251 EAST   52 STREET                  101052     10022  40.756598 -73.968691  Turtle Bay-East Midtown
34974  Manhattan  BELLA LUNA RESTAURANT          both    BLTG PIZZA INC DBA BELLA LUNA  574 574 Columbus Avenue                    2118     10024        NaN        NaN                      NaN

     Borough       RestaurantName SeatingChoice        LegalBusinessName    BusinessAddress  RestaurantInspectionID  Postcode   Latitude  Longitude                                         NTA
0  Manhattan          Oscar Wilde          both       Camelot Castle LLC   45  West 27th st                   72891     10001  40.744876 -73.989657  Hudson Yards-Chelsea-Flatiron-Union Square
1  Manhattan  LA RUBIA RESTAURANT          both  LA RUBIA RESTAURANT INC      3517 BROADWAY                   72892     10031  40.825863 -73.950874                            Hamilton Heights
2  Manhattan         Thai Sliders      sidewalk           Silom Thai Inc      150   8th Ave                   72893     10011  40.741906 -74.000945  Hudson Yards-Chelsea-Flatiron-Union Square
5  Manhattan         LURE FISHBAR          both    142 MERCER STREET LLC  142 MERCER STREET                   72897     10012  40.724837 -73.998402      SoHo-TriBeCa-Civic Center-Little Italy
6  Manhattan         Mojo omakase          both            Mojo chef inc     177 9th avenue                   72898     10011  40.744917 -74.002487  Hudson Yards-Chelsea-Flatiron-Union Square

In [22]:
# Save the cleaned DataFrame to a new CSV file
df_manhattan_cleaned.to_csv('Cleaned_Open_Restaurants_Inspections_20250408.csv', index=False)
print("Exported successfully!")

Exported successfully!

In [29]:
import pandas as pd
import json

# Load the inspections dataset
df = pd.read_csv("Cleaned_Open_Restaurants_Inspections_20250408.csv")

# Drop rows without coordinates
df_clean = df.dropna(subset=["Latitude", "Longitude"])

# Convert each row into a GeoJSON Feature
def row_to_feature(row):
    return {
        "type": "Feature",
        "geometry": {
            "type": "Point",
            "coordinates": [row["Longitude"], row["Latitude"]],
        },
        "properties": {
            "restaurant_name": row["RestaurantName"],
            "borough": row["Borough"],
            "address": row["BusinessAddress"],
            "legal_name": row["LegalBusinessName"],
            "seating_choice": row["SeatingChoice"],
            "inspection_id": row["RestaurantInspectionID"],
            "nta": row["NTA"]
        }
    }

# Convert the DataFrame to a list of GeoJSON features
features = [row_to_feature(row) for _, row in df_clean.iterrows()]

# Create the final GeoJSON structure
geojson = {
    "type": "FeatureCollection",
    "features": features
}

# Save to file
with open("Open_Restaurants_Inspections_20250408.geojson", "w") as f:
    json.dump(geojson, f, indent=2)

print("GeoJSON file created as 'Open_Restaurants_Inspections_20250408.geojson'")

GeoJSON file created as 'Open_Restaurants_Inspections_20250408.geojson'